server.port=8088
spring.application.name=INTERVIEW-SERVICE
spring.datasource.url=jdbc:mysql://localhost:3306/talenttalk_interview?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Roman123@.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
ollama.api.url=http://localhost:11434/api/generate
ollama.model=llama3.2